# Generated by Django 5.2.2 on 2026-03-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_category_recipe_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.png', upload_to='recipes/'),
        ),
    ]
